%YAML:1.0

#common parameters
imu_topic: "/camera/imu"
image_topic: "/camera/infra1/image_rect_raw"
output_path: "/home/fish/code/mvins_ws/src/VINS-Mono/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 848
image_height: 480
distortion_parameters:
   k1: 0.0014328228810726253
   k2: -0.0015156344001513776
   p1: 0.0006062126216491875
   p2: 0.0018711579646681084
projection_parameters:
   fx: 426.6168298679971
   fy: 427.3598222958435
   cx: 427.87554730563954
   cy: 238.07662004523834
# Camera.fx: 427.1324462890625
# Camera.fy: 427.1324462890625
# Camera.cx: 422.80657958984375
# Camera.cy: 245.63272094726562
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.99981, 0.00845925, 0.0175764,
           -0.00836923, 0.999952, -0.00518873,
           -0.0176194, 0.00504064, 0.999832]
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -0.027442, 0.00551397, 0.00114287 ]

#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 25            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.1 #3 #0.1   # max solver itration time (ms), to guarantee real time
max_num_iterations: 10 #10 #8  # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.001         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 0.0001      # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007      # gravity magnitude

#loop closure parameters
loop_closure: 1                 # start loop closure
load_previous_pose_graph: 0     # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0          # useful in real-time and large project
pose_graph_save_path: "/home/fish/code/mvins_ws/src/VINS-Mono/pose_graph/" # save and load path

#unsynchronization parameters
estimate_td: 0                      # online estimate time offset between camera and imu
td: 0.00                            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

#lines
#lines
min_line_length: 15 
line_fit_err: 1.8 
vp_factor: 1.0 
# feature selector
use_feature_selector: 0          # 1: enable the attention algorithm for feature selection
max_features: 30                 # number of features to maintain
init_threshold: 30               # during initialization, don't go below this many features
use_ground_truth_hgen: 0         # 0: use latest imu measurement to simulate forward; 1: use ground 